[package]
name = "dyndns"
version = "0.2.0"
authors = ["Alexander Kudrevatykh <alexander@kudrevatykh.com>"]
edition = "2018"

[dependencies]
hyper = "0.13.1"
hyper-tls = "0.4.1"
tokio = {version = "0.2.9", features=["full"] }
