[package]
name = "dyndns"
version = "0.1.1"
authors = ["Alexander Kudrevatykh <alexander@kudrevatykh.com>"]

[dependencies]
futures = "0.1.18"
hyper = "0.11.22"
hyper-tls = "0.1.2"
tokio-core = "0.1.15"
